{% set version = "1.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cli
  version: {{ version|replace("-", "_") }}

source:
  fn: cli_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/cli_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cli/cli_{{ version }}.tar.gz
  sha256: 4fc00fcdf4fdbdf9b5792faee8c7cf1ed5c4f45b1221d961332cda82dbe60d0a

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-assertthat
    - r-crayon >=1.3.4

  run:
    - r-base
    - r-assertthat
    - r-crayon >=1.3.4

test:
  commands:
    - $R -e "library('cli')"           # [not win]
    - "\"%R%\" -e \"library('cli')\""  # [win]

about:
  home: https://github.com/r-lib/cli
  license: MIT
  summary: A suite of tools designed to build attractive command line interfaces ('CLIs'). Includes
    tools for drawing rules, boxes, trees, and 'Unicode' symbols with 'ASCII' alternatives.
  license_family: MIT
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\MIT'  # [win]

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
