{% set version = "2.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cli
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cli_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cli/cli_{{ version }}.tar.gz
  sha256: 5067dfbe056a4b2a57142520f4895ec0b018d3065a910ff4ca41444019b58d9c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertthat
    - r-crayon >=1.3.4
    - r-glue
    - r-fansi
  run:
    - r-base
    - r-assertthat
    - r-crayon >=1.3.4
    - r-glue
    - r-fansi

test:
  commands:
    - $R -e "library('cli')"           # [not win]
    - "\"%R%\" -e \"library('cli')\""  # [win]

about:
  home: https://github.com/r-lib/cli
  license: MIT
  summary: A suite of tools designed to build attractive command line interfaces ('CLIs'). Includes tools for drawing rules, boxes, trees, and 'Unicode' symbols with 'ASCII' alternatives.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: cli
# Title: Helpers for Developing Command Line Interfaces
# Version: 1.1.0
# Authors@R: c( person("Gabor", "Csardi", , "csardi.gabor@gmail.com", c("aut", "cre")), person("Hadley", "Wickham", role = c("ctb")), person("Kirill", "Muller", role = c("ctb")) )
# Description: A suite of tools designed to build attractive command line interfaces ('CLIs'). Includes tools for drawing rules, boxes, trees, and 'Unicode' symbols with 'ASCII' alternatives.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/cli#readme
# BugReports: https://github.com/r-lib/cli/issues
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# Imports: assertthat, crayon (>= 1.3.4), methods, utils
# Suggests: covr, fansi, mockery, testthat, webshot, withr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-03-19 09:55:47 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre], Hadley Wickham [ctb], Kirill Muller [ctb]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-03-19 10:43:26 UTC
