{% set version = "3.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cli
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cli_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cli/cli_{{ version }}.tar.gz
  sha256: c8b3e6014ad60593ba21897255acfe90c0e3f98bd4f7e22c1f3acb2644cf54cf

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-glue                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-glue

test:
  commands:
    - $R -e "library('cli')"           # [not win]
    - "\"%R%\" -e \"library('cli')\""  # [win]

about:
  home: https://cli.r-lib.org, https://github.com/r-lib/cli#readme
  license: MIT
  summary: "A suite of tools to build attractive command line interfaces ('CLIs'), from semantic elements: headings, lists, alerts, paragraphs, etc. Supports custom themes via a 'CSS'-like language. It also contains a number of lower level 'CLI' elements: rules, boxes, trees, and 'Unicode' symbols with 'ASCII' alternatives.\
    \ It support ANSI colors and text styles as well."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: cli
# Title: Helpers for Developing Command Line Interfaces
# Version: 3.0.1
# Authors@R: c( person("Gabor", "Csardi", , "csardi.gabor@gmail.com", c("aut", "cre")), person("Hadley", "Wickham", role = c("ctb")), person("Kirill", "Muller", role = c("ctb")), person("RStudio", role = "cph") )
# Description: A suite of tools to build attractive command line interfaces ('CLIs'), from semantic elements: headings, lists, alerts, paragraphs, etc. Supports custom themes via a 'CSS'-like language. It also contains a number of lower level 'CLI' elements: rules, boxes, trees, and 'Unicode' symbols with 'ASCII' alternatives. It support ANSI colors and text styles as well.
# License: MIT + file LICENSE
# URL: https://cli.r-lib.org, https://github.com/r-lib/cli#readme
# BugReports: https://github.com/r-lib/cli/issues
# RoxygenNote: 7.1.1.9001
# Depends: R (>= 2.10)
# Imports: glue, utils
# Suggests: callr, covr, grDevices, htmlwidgets, knitr, methods, mockery, prettycode (>= 1.1.0), processx, ps (>= 1.3.4.9000), rlang, rmarkdown, rstudioapi, shiny, testthat, tibble, withr
# Config/testthat/edition: 3
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2021-07-16 20:08:00 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre], Hadley Wickham [ctb], Kirill Muller [ctb], RStudio [cph]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-07-17 09:00:01 UTC
