travis:
  secure:
    BINSTAR_TOKEN: cA6oQZcLe0Wnx5bE2989+X5nuG0c6NfsLxLged1WXy1qrcXGQHFoBlLj5lUUIGtI+ChPMWDAskShgNJRz/LSNRTohQRQ8lsKM1bT/tNn8YtZS3larme8UZG5uWAKjC8VSz0FARE/O5MSMbOaYoUDFvzEqqF0awz0RmpmmH1MEKZ7N9dXB/O5zdzvLJXKIlIAjK1eKJTHOdaL0kkot/R1YxbuBupTrDDPhPyEMUvlWutaBexjjJ7jwqxrvY4brTOFJZx7nfMxeQmdXTDHv7XxG08AeJSN6jqWjQ9YxIO4rlRymnfCprqc739zzKPEPzShEbkIIM+4Tkz3iXqNgtOpNaRI1UDB7FLpb2C1H1/J4BCpXBoApfCMRw/lKZjZXdEHeheQkpynmUXhxdDiQFpfHzg8AX7dGLfGuuBYfdpkIDyx1hoZ+agjthU2cVMwJQthxSpwjxIy7KBZGXfnuQPXD07Xhzy3wM7uSDfm9zzpoVO/ZggRtadbcB4LSCzZq6GEmZUaF2RYTapkSCAKv/oT1OUFnxzoe1kGk54UZdszEAh+i1J136H2L5xqBo8ZAsbslf2KOuGAf2mYL24v1fI8nmygcB7yf+WKfYl7lADZT+lQgFP2Ye4ffUgSw2ccQCq4J2oGezv+n0i1GpJMG/QUFesIDKewAn1h5IDY+pT+9KY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
